FROM node:10.15.3-alpine

WORKDIR /var/www

# Install app deps. Workaround to cache yarn install
ADD package.json package.json
ADD yarn.lock yarn.lock
RUN yarn install

# Copy source codes
ADD . /var/www

# ENVS
ARG ISSUE_FINDER_SOURCE_CONTROL_PROVIDER=''
ENV ISSUE_FINDER_SOURCE_CONTROL_PROVIDER=$ISSUE_FINDER_SOURCE_CONTROL_PROVIDER

ARG ISSUE_FINDER_SOURCE_CONTROL_ACCOUNT=''
ENV ISSUE_FINDER_SOURCE_CONTROL_ACCOUNT=$ISSUE_FINDER_SOURCE_CONTROL_ACCOUNT

ARG ISSUE_FINDER_SOURCE_CONTROL_REPO=''
ENV ISSUE_FINDER_SOURCE_CONTROL_REPO=$ISSUE_FINDER_SOURCE_CONTROL_REPO

ARG ISSUE_FINDER_SOURCE_CONTROL_REPO_NAME=''
ENV ISSUE_FINDER_SOURCE_CONTROL_REPO_NAME=$ISSUE_FINDER_SOURCE_CONTROL_REPO_NAME

# Build
RUN yarn build

# Clear yarn cache to reduce image size
RUN yarn cache clean

CMD ["yarn", "start"]
